POST http://localhost:8000/api/login
Content-Type: application/json

{
    "username": "abe55",
    "password": "password"
}

POST http://localhost:8000/api/invoice
Content-Type: application/json

{
    "username": "abe55",
    "password": "password"
}
