<?php

return [
    "users" => [
        "pemungut" => [
            [
                "No" => "1",
                "name" => "Sahat Gurning",
                "nik" => "",
                "email" => "",
                "gender" => "Laki-laki",
                "sub_district_id" => 1,
                "phoneNumber" => "081361064594",
                "address" => "Balige"
            ],
            [
                "No" => "2",
                "name" => "Brusli Silitonga",
                "nik" => "",
                "email" => "",
                "gender" => "Laki-laki",
                "sub_district_id" => 1,
                "phoneNumber" => "081397668155",
                "address" => "Balige"
            ],
            [
                "No" => "3",
                "name" => "Linggom Saunders",
                "nik" => "",
                "email" => "",
                "gender" => "Laki-laki",
                "sub_district_id" => 1,
                "phoneNumber" => "085215065552",
                "address" => "Balige"
            ],
            [
                "No" => "4",
                "name" => "Heri Saragih",
                "nik" => "",
                "email" => "",
                "gender" => "Laki-laki",
                "sub_district_id" => 1,
                "phoneNumber" => "08126074513",
                "address" => "Balige"
            ],
            [
                "No" => "5",
                "name" => "Abner Sirait ",
                "nik" => "",
                "email" => "",
                "gender" => "Laki-laki",
                "sub_district_id" => 1,
                "phoneNumber" => "082162913277",
                "address" => "Balige"
            ],
            [
                "No" => "6",
                "name" => "Bonari Siahaan",
                "nik" => "",
                "email" => "",
                "gender" => "Laki-laki",
                "sub_district_id" => 1,
                "phoneNumber" => "081372608612",
                "address" => "Balige"
            ],
            [
                "No" => "7",
                "name" => "Hasiholan Tambunan",
                "nik" => "",
                "email" => "",
                "gender" => "Laki-laki",
                "sub_district_id" => 1,
                "phoneNumber" => "081365259778",
                "address" => "Balige"
            ],
            [
                "No" => "8",
                "name" => "Jenni Napitupulu",
                "nik" => "",
                "email" => "",
                "gender" => "Laki-laki",
                "sub_district_id" => 1,
                "phoneNumber" => "081276905313",
                "address" => "Silaen"
            ],
            [
                "No" => "9",
                "name" => "James Simanjuntak",
                "nik" => "",
                "email" => "",
                "gender" => "Laki-laki",
                "sub_district_id" => 18,
                "phoneNumber" => "081262139039",
                "address" => "Balige"
            ],
            [
                "No" => "10",
                "name" => "Refloni Sinaga",
                "nik" => "",
                "email" => "",
                "gender" => "Laki-laki",
                "sub_district_id" => 3,
                "phoneNumber" => "085365629201",
                "address" => "Laguboti"
            ],
            [
                "No" => "11",
                "name" => "Litekly Ompusunggu",
                "nik" => "",
                "email" => "",
                "gender" => "Laki-laki",
                "sub_district_id" => 9,
                "phoneNumber" => "085270694121",
                "address" => "Porsea"
            ],
            [
                "No" => "12",
                "name" => "Dendy Napitupulu",
                "nik" => "",
                "email" => "",
                "gender" => "Laki-laki",
                "sub_district_id" => 7,
                "phoneNumber" => "081272914616",
                "address" => "Silaen"
            ],
            [
                "No" => "13",
                "name" => "Darwin Sinaga",
                "nik" => "",
                "email" => "",
                "gender" => "Laki-laki",
                "sub_district_id" => 4,
                "phoneNumber" => "085211389302",
                "address" => "Habinsaran"
            ],
            [
                "No" => "14",
                "name" => "Jefry Santoro Samosir",
                "nik" => "",
                "email" => "",
                "gender" => "Laki-laki",
                "sub_district_id" => 15,
                "phoneNumber" => "081362289353",
                "address" => "Ajibata"
            ],
            [
                "No" => "15",
                "name" => "Jhon Roy Pangaribuan",
                "nik" => "",
                "email" => "",
                "gender" => "Laki-laki",
                "sub_district_id" => 17,
                "phoneNumber" => "082166243600",
                "address" => "Laguboti"
            ]
        ],
        "masyarakat" => array(
            array("id" => "1", "name" => "TK Garden", "email" => "", "username" => "tk_garden", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Gereja", "phoneNumber" => "81237485001", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "1", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Gereja", 'pemungut_id' => 1),
            array("id" => "2", "name" => "TK Klinton", "email" => "", "username" => "tk_klinton", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Gereja", "phoneNumber" => "81237485002", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "2", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Gereja", 'pemungut_id' => 1),
            array("id" => "3", "name" => "TK Lisbet", "email" => "", "username" => "tk_lisbet", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Gereja", "phoneNumber" => "81237485003", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "3", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Gereja", 'pemungut_id' => 1),
            array("id" => "4", "name" => "Neccis Ponsel", "email" => "", "username" => "neccis_ponsel", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Gereja", "phoneNumber" => "81237485004", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "4", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Gereja", 'pemungut_id' => 1),
            array("id" => "5", "name" => "YOEL Salon", "email" => "", "username" => "yoel_salon", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Gereja", "phoneNumber" => "81237485005", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "5", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Gereja", 'pemungut_id' => 1),
            array("id" => "6", "name" => "Praktek Siburian", "email" => "", "username" => "praktek_siburian", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Gereja", "phoneNumber" => "81237485006", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "6", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Gereja", 'pemungut_id' => 1),
            array("id" => "7", "name" => "Kantor BPOM", "email" => "", "username" => "kantor_bpom", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Gereja", "phoneNumber" => "81237485007", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "7", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Gereja", 'pemungut_id' => 1),
            array("id" => "8", "name" => "R.Makan Restu", "email" => "", "username" => "rumah_makan_restu", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Gereja", "phoneNumber" => "81237485008", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "8", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Gereja", 'pemungut_id' => 1),
            array("id" => "9", "name" => "Metro", "email" => "", "username" => "metro", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Gereja", "phoneNumber" => "81237485009", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "9", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Gereja", 'pemungut_id' => 1),
            array("id" => "10", "name" => "Toko. R. Hutagaol", "email" => "", "username" => "toko_r_hutagaol", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Gereja", "phoneNumber" => "81237485010", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "10", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Gereja", 'pemungut_id' => 1),
            array("id" => "11", "name" => "Mrs. Aqua", "email" => "", "username" => "mrs_aqua", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Gereja", "phoneNumber" => "81237485011", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "11", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Gereja", 'pemungut_id' => 1),
            array("id" => "12", "name" => "Warung mama Weri", "email" => "", "username" => "warung_mama_weri", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Gereja", "phoneNumber" => "81237485012", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "12", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Gereja", 'pemungut_id' => 1),
            array("id" => "13", "name" => "Given Hoky Cell", "email" => "", "username" => "given_hoky_cell", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Gereja", "phoneNumber" => "81237485013", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "13", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Gereja", 'pemungut_id' => 1),
            array("id" => "14", "name" => "Salon Eka", "email" => "", "username" => "salon_eka", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Gereja", "phoneNumber" => "81237485014", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "14", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Gereja", 'pemungut_id' => 1),
            array("id" => "15", "name" => "Bang Boy Kolding", "email" => "", "username" => "bang_boy_kolding", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Gereja", "phoneNumber" => "81237485015", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "15", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Gereja", 'pemungut_id' => 1),
            array("id" => "16", "name" => "Gorden Jaya", "email" => "", "username" => "gorden_jaya", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Gereja", "phoneNumber" => "81237485016", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "16", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Gereja", 'pemungut_id' => 1),
            array("id" => "17", "name" => "Bakmi Saudara", "email" => "", "username" => "bakmi_saudara", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Gereja", "phoneNumber" => "81237485017", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "17", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Gereja", 'pemungut_id' => 1),
            array("id" => "18", "name" => "Balige Cipta Net", "email" => "", "username" => "balige_cipta_net", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Gereja", "phoneNumber" => "81237485018", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "18", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Gereja", 'pemungut_id' => 1),
            array("id" => "19", "name" => "E. Siahaan", "email" => "", "username" => "e_siahaan", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Gereja", "phoneNumber" => "81237485019", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "19", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Gereja", 'pemungut_id' => 1),
            array("id" => "20", "name" => "Laundry", "email" => "", "username" => "laundry", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Gereja", "phoneNumber" => "81237485020", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "20", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Gereja", 'pemungut_id' => 1),
            array("id" => "21", "name" => "Secom", "email" => "", "username" => "secom", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Gereja", "phoneNumber" => "81237485021", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "21", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Gereja", 'pemungut_id' => 1),
            array("id" => "22", "name" => "Kedai Sinambela", "email" => "", "username" => "kedai_sinambela", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Gereja", "phoneNumber" => "81237485022", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "22", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Gereja", 'pemungut_id' => 1),
            array("id" => "23", "name" => "Sury Tailor", "email" => "", "username" => "sury_tailor", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Gereja", "phoneNumber" => "81237485023", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "23", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Gereja", 'pemungut_id' => 1),
            array("id" => "24", "name" => "Servis CMS", "email" => "", "username" => "servis_cms", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Gereja", "phoneNumber" => "81237485024", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "24", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Gereja", 'pemungut_id' => 1),
            array("id" => "25", "name" => "Salon Ros", "email" => "", "username" => "salon_ros", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Gereja", "phoneNumber" => "81237485025", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "25", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Gereja", 'pemungut_id' => 1),
            array("id" => "26", "name" => "Fotocopy Lina", "email" => "", "username" => "fotocopy_lina", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Gereja", "phoneNumber" => "81237485026", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "26", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Gereja", 'pemungut_id' => 1),
            array("id" => "27", "name" => "Salon Lina", "email" => "", "username" => "salon_lina", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Gereja", "phoneNumber" => "81237485027", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "27", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Gereja", 'pemungut_id' => 1),
            array("id" => "28", "name" => "Bonbon", "email" => "", "username" => "bonbon", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Gereja", "phoneNumber" => "81237485028", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "28", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Gereja", 'pemungut_id' => 1),
            array("id" => "29", "name" => "Bengkel Padang", "email" => "", "username" => "bengkel_padang", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Patuan Anggi", "phoneNumber" => "81237485029", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "29", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Patuan Anggi", 'pemungut_id' => 1),
            array("id" => "30", "name" => "Mukni", "email" => "", "username" => "mukni", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Patuan Anggi", "phoneNumber" => "81237485030", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "30", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Patuan Anggi", 'pemungut_id' => 1),
            array("id" => "31", "name" => "Toko Usaha Baru", "email" => "", "username" => "toko_usaha_baru", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Patuan Anggi", "phoneNumber" => "81237485031", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "31", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Patuan Anggi", 'pemungut_id' => 1),
            array("id" => "32", "name" => "Toko Caniago", "email" => "", "username" => "toko_caniago", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Patuan Anggi", "phoneNumber" => "81237485032", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "32", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Patuan Anggi", 'pemungut_id' => 1),
            array("id" => "33", "name" => "Toko Conny", "email" => "", "username" => "toko_conny", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Patuan Anggi", "phoneNumber" => "81237485033", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "33", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Patuan Anggi", 'pemungut_id' => 1),
            array("id" => "34", "name" => "Penjahit Ma Leo", "email" => "", "username" => "penjahit_ma_leo", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Patuan Anggi", "phoneNumber" => "81237485034", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "34", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Patuan Anggi", 'pemungut_id' => 1),
            array("id" => "35", "name" => "Kedai Siahaan", "email" => "", "username" => "kedai_siahaan", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Patuan Anggi", "phoneNumber" => "81237485035", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "35", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Patuan Anggi", 'pemungut_id' => 1),
            array("id" => "36", "name" => "Fres Seafood", "email" => "", "username" => "fres_seafood", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Patuan Anggi", "phoneNumber" => "81237485036", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "36", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Patuan Anggi", 'pemungut_id' => 1),
            array("id" => "37", "name" => "Bengkel Las Roha", "email" => "", "username" => "bengkel_las_roha", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Patuan Anggi", "phoneNumber" => "81237485037", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "37", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Patuan Anggi", 'pemungut_id' => 1),
            array("id" => "38", "name" => "UD Sitinjak", "email" => "", "username" => "ud_sitinjak", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Patuan Anggi", "phoneNumber" => "81237485038", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "38", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Patuan Anggi", 'pemungut_id' => 1),
            array("id" => "39", "name" => "Bengkel Simajuntak", "email" => "", "username" => "bengkel_simanjuntak", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Patuan Anggi", "phoneNumber" => "81237485039", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "39", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Patuan Anggi", 'pemungut_id' => 1),
            array("id" => "40", "name" => "Toko Emas HR. Hasibuan", "email" => "", "username" => "toko_emas_hr_hasibuan", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Patuan Anggi", "phoneNumber" => "81237485040", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "40", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Patuan Anggi", 'pemungut_id' => 1),
            array("id" => "41", "name" => "Toko Tembakau", "email" => "", "username" => "toko_tembakau", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Patuan Anggi", "phoneNumber" => "81237485041", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "41", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Patuan Anggi", 'pemungut_id' => 1),
            array("id" => "42", "name" => "Toko B. HUtagaol", "email" => "", "username" => "toko_b_hutagaol", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Patuan Anggi", "phoneNumber" => "81237485042", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "42", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Patuan Anggi", 'pemungut_id' => 1),
            array("id" => "43", "name" => "Toko Emas Rasoki S", "email" => "", "username" => "toko_emas_rasoki_s", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Patuan Anggi", "phoneNumber" => "81237485043", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "43", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Patuan Anggi", 'pemungut_id' => 1),
            array("id" => "44", "name" => "Warung Ma Uli", "email" => "", "username" => "warung_ma_uli", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Patuan Anggi", "phoneNumber" => "81237485044", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "44", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Patuan Anggi", 'pemungut_id' => 1),
            array("id" => "45", "name" => "Una Pardede", "email" => "", "username" => "una_pardede", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Patuan Anggi", "phoneNumber" => "81237485045", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "45", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Patuan Anggi", 'pemungut_id' => 1),
            array("id" => "46", "name" => "Pangeran Napitupulu", "email" => "", "username" => "pangeran_napitupulu", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Patuan Anggi", "phoneNumber" => "81237485046", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "46", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Patuan Anggi", 'pemungut_id' => 1),
            array("id" => "47", "name" => "Toko serba 35", "email" => "", "username" => "toko_serba_35", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Patuan Anggi", "phoneNumber" => "81237485047", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "47", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Patuan Anggi", 'pemungut_id' => 1),
            array("id" => "48", "name" => "Yosua Optik", "email" => "", "username" => "yosua_optik", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Patuan Anggi", "phoneNumber" => "81237485048", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "48", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Patuan Anggi", 'pemungut_id' => 1),
            array("id" => "49", "name" => "Toko Sinur", "email" => "", "username" => "toko_sinur", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Patuan Anggi", "phoneNumber" => "81237485049", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "49", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Patuan Anggi", 'pemungut_id' => 1),
            array("id" => "50", "name" => "Toko Osing", "email" => "", "username" => "toko_osing", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Patuan Anggi", "phoneNumber" => "81237485050", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "50", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Patuan Anggi", 'pemungut_id' => 1),
            array("id" => "51", "name" => "Toko R, Sianipar", "email" => "", "username" => "toko_r_sianipar", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Patuan Anggi", "phoneNumber" => "81237485051", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "51", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Patuan Anggi", 'pemungut_id' => 1),
            array("id" => "52", "name" => "Toko Tani Jaya", "email" => "", "username" => "toko_tani_jaya", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Patuan Anggi", "phoneNumber" => "81237485052", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "52", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Patuan Anggi", 'pemungut_id' => 1),
            array("id" => "53", "name" => "UD. M Sihombing", "email" => "", "username" => "ud_m_sihombing", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Patuan Anggi", "phoneNumber" => "81237485053", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "53", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Patuan Anggi", 'pemungut_id' => 1),
            array("id" => "54", "name" => "UD. Hutagalung", "email" => "", "username" => "ud_hutagalung", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Patuan Anggi", "phoneNumber" => "81237485054", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "54", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Patuan Anggi", 'pemungut_id' => 1),
            array("id" => "55", "name" => "Toko Nelson", "email" => "", "username" => "toko_nelson", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. TB. Simatupang", "phoneNumber" => "81237485055", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "55", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. TB. Simatupang", 'pemungut_id' => 1),
            array("id" => "56", "name" => "Toko Emas Hasibuan", "email" => "", "username" => "toko_emas_hasibuan", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. TB. Simatupang", "phoneNumber" => "81237485056", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "56", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. TB. Simatupang", 'pemungut_id' => 1),
            array("id" => "57", "name" => "Toko B. Simangunsong", "email" => "", "username" => "toko_b_simangunsong", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. TB. Simatupang", "phoneNumber" => "81237485057", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "57", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. TB. Simatupang", 'pemungut_id' => 1),
            array("id" => "58", "name" => "W. Siahaan", "email" => "", "username" => "w_siahaan", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. TB. Simatupang", "phoneNumber" => "81237485058", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "58", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. TB. Simatupang", 'pemungut_id' => 1),
            array("id" => "59", "name" => "Toko Anda", "email" => "", "username" => "toko_anda", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. TB. Simatupang", "phoneNumber" => "81237485059", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "59", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. TB. Simatupang", 'pemungut_id' => 1),
            array("id" => "60", "name" => "Toko Seia sekata", "email" => "", "username" => "toko_seia_sekata", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. TB. Simatupang", "phoneNumber" => "81237485060", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "60", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. TB. Simatupang", 'pemungut_id' => 1),
            array("id" => "61", "name" => "Ester Store", "email" => "", "username" => "ester_store", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. TB. Simatupang", "phoneNumber" => "81237485061", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "61", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. TB. Simatupang", 'pemungut_id' => 1),
            array("id" => "62", "name" => "Toko Marlina", "email" => "", "username" => "toko_marlina", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. TB. Simatupang", "phoneNumber" => "81237485062", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "62", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. TB. Simatupang", 'pemungut_id' => 1),
            array("id" => "63", "name" => "Junior Siahaan", "email" => "", "username" => "junior_siahaan", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. TB. Simatupang", "phoneNumber" => "81237485063", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "63", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. TB. Simatupang", 'pemungut_id' => 1),
            array("id" => "64", "name" => "Warung Ma Renty", "email" => "", "username" => "warung_ma_renty", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. TB. Simatupang", "phoneNumber" => "81237485064", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "64", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. TB. Simatupang", 'pemungut_id' => 1),
            array("id" => "65", "name" => "Toko H. Sihombing", "email" => "", "username" => "toko_h_sihombing", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. TB. Simatupang", "phoneNumber" => "81237485065", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "65", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. TB. Simatupang", 'pemungut_id' => 1),
            array("id" => "66", "name" => "Warung S. Saryfa", "email" => "", "username" => "warung_s_saryfa", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Paindoan", "phoneNumber" => "81237485066", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "66", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Paindoan", 'pemungut_id' => 1),
            array("id" => "67", "name" => "UD. Valentino", "email" => "", "username" => "ud_valentino", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Paindoan", "phoneNumber" => "81237485067", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "67", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Paindoan", 'pemungut_id' => 1),
            array("id" => "68", "name" => "Rikardo Taylor", "email" => "", "username" => "rikardo_taylor", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Paindoan", "phoneNumber" => "81237485068", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "68", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Paindoan", 'pemungut_id' => 1),
            array("id" => "69", "name" => "Tukang Kayu Tambunan", "email" => "", "username" => "tukang_kayu_tambunan", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Paindoan", "phoneNumber" => "81237485069", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "69", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Paindoan", 'pemungut_id' => 1),
            array("id" => "70", "name" => "UD. Pardede", "email" => "", "username" => "ud_pardede", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Paindoan", "phoneNumber" => "81237485070", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "70", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Paindoan", 'pemungut_id' => 1),
            array("id" => "71", "name" => "Warung Harahap", "email" => "", "username" => "warung_harahap", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Paindoan", "phoneNumber" => "81237485071", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "71", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Paindoan", 'pemungut_id' => 1),
            array("id" => "72", "name" => "Toko Cahaya", "email" => "", "username" => "toko_cahaya", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Somba Debata", "phoneNumber" => "81237485072", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "72", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Somba Debata", 'pemungut_id' => 1),
            array("id" => "73", "name" => "Warung M. Simanjutak", "email" => "", "username" => "warung_m_simanjuntak", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Jambu", "phoneNumber" => "81237485073", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "73", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Jambu", 'pemungut_id' => 1),
            array("id" => "74", "name" => "Tempat Kos Partungkoan", "email" => "", "username" => "tempat_kos_partungkoan", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Gereja", "phoneNumber" => "81237485074", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "74", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Gereja", 'pemungut_id' => 1),
            array("id" => "75", "name" => "Boz Barber", "email" => "", "username" => "boz_barber", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Gereja", "phoneNumber" => "81237485075", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "75", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Gereja", 'pemungut_id' => 1),
            array("id" => "76", "name" => "M. Simanjuntak", "email" => "", "username" => "m_simanjuntak", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Pasar Tambunan", "phoneNumber" => "81237485076", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "76", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Pasar Tambunan", 'pemungut_id' => 1),
            array("id" => "77", "name" => "Pangkas Zebua", "email" => "", "username" => "pangkas_zebua", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Pasar Tambunan", "phoneNumber" => "81237485077", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "77", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Pasar Tambunan", 'pemungut_id' => 1),
            array("id" => "78", "name" => "Bidan Lumbangaol", "email" => "", "username" => "bidan_lumbangaol", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Pasar Tambunan", "phoneNumber" => "81237485078", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "78", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Pasar Tambunan", 'pemungut_id' => 1),
            array("id" => "79", "name" => "Toko MN. Tambunan", "email" => "", "username" => "toko_mn_tambunan", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Pasar Tambunan", "phoneNumber" => "81237485079", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "79", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Pasar Tambunan", 'pemungut_id' => 1),
            array("id" => "80", "name" => "Ardin Tampubolon", "email" => "", "username" => "ardin_tampubolon", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Pasar Tambunan", "phoneNumber" => "81237485080", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "80", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Pasar Tambunan", 'pemungut_id' => 1),
            array("id" => "81", "name" => "Yohana Tambunan", "email" => "", "username" => "yohana_tambunan", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Pasar Tambunan", "phoneNumber" => "81237485081", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "81", "category_id" => "2", "sub_district_id" => "1", "address_uc" => "Jl. Pasar Tambunan", 'pemungut_id' => 1),
            array("id" => "82", "name" => "BM Motor", "email" => "", "username" => "bm_motor", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Gereja", "phoneNumber" => "81237485082", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "82", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Jl. Gereja", 'pemungut_id' => 1),
            array("id" => "83", "name" => "Kedai Tampubolon", "email" => "", "username" => "kedai_tampubolon", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Gereja", "phoneNumber" => "81237485083", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "83", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Jl. Gereja", 'pemungut_id' => 1),
            array("id" => "84", "name" => "Larisma", "email" => "", "username" => "larisma", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Gereja", "phoneNumber" => "81237485084", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "84", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Jl. Gereja", 'pemungut_id' => 1),
            array("id" => "85", "name" => "Aris", "email" => "", "username" => "aris", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Gereja", "phoneNumber" => "81237485085", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "85", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Jl. Gereja", 'pemungut_id' => 1),
            array("id" => "86", "name" => "Sumatera Taylor", "email" => "", "username" => "sumatera_taylor", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Patuan Anggi", "phoneNumber" => "81237485086", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "86", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Jl. Patuan Anggi", 'pemungut_id' => 1),
            array("id" => "87", "name" => "Ines (dame)", "email" => "", "username" => "ines", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Patuan Anggi", "phoneNumber" => "81237485087", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "87", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Jl. Patuan Anggi", 'pemungut_id' => 1),
            array("id" => "88", "name" => "Jillam Tampubolon", "email" => "", "username" => "jilam_tampubolon", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Patuan Anggi", "phoneNumber" => "81237485088", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "88", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Jl. Patuan Anggi", 'pemungut_id' => 1),
            array("id" => "89", "name" => "Mas Dian", "email" => "", "username" => "mas_dian", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Patuan Anggi", "phoneNumber" => "81237485089", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "89", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Jl. Patuan Anggi", 'pemungut_id' => 1),
            array("id" => "90", "name" => "Setia Siahaan", "email" => "", "username" => "setia_siahaan", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Patuan Anggi", "phoneNumber" => "81237485090", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "90", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Jl. Patuan Anggi", 'pemungut_id' => 1),
            array("id" => "91", "name" => "P. Muti", "email" => "", "username" => "p_muti", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Patuan Anggi", "phoneNumber" => "81237485091", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "91", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Jl. Patuan Anggi", 'pemungut_id' => 1),
            array("id" => "92", "name" => "Ma Catrin", "email" => "", "username" => "ma_catrin", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Patuan Anggi", "phoneNumber" => "81237485092", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "92", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Jl. Patuan Anggi", 'pemungut_id' => 1),
            array("id" => "93", "name" => "Barungge", "email" => "", "username" => "barungge", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Patuan Anggi", "phoneNumber" => "81237485093", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "93", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Jl. Patuan Anggi", 'pemungut_id' => 1),
            array("id" => "94", "name" => "Rosa", "email" => "", "username" => "rosa", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Patuan Anggi", "phoneNumber" => "81237485094", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "94", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Jl. Patuan Anggi", 'pemungut_id' => 1),
            array("id" => "95", "name" => "M. Natanael", "email" => "", "username" => "m_natanael", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Patuan Anggi", "phoneNumber" => "81237485095", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "95", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Jl. Patuan Anggi", 'pemungut_id' => 1),
            array("id" => "2", "name" => "Toko Sianipar", "email" => "", "username" => "toko_sianipar", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Patuan Anggi", "phoneNumber" => "81237485096", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "2", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Jl. Patuan Anggi", 'pemungut_id' => 1),
            array("id" => "97", "name" => "U. Pasaribu", "email" => "", "username" => "u_pasaribu", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. TB Simatupang", "phoneNumber" => "81237485097", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "97", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Jl. TB Simatupang", 'pemungut_id' => 1),
            array("id" => "98", "name" => "Gr. P Sibuea", "email" => "", "username" => "gr_p_sibuea", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. GHM Siahaan", "phoneNumber" => "81237485098", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "98", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Jl. GHM Siahaan", 'pemungut_id' => 1),
            array("id" => "99", "name" => "Pdt. Gultom", "email" => "", "username" => "pdt_gultom", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. GHM Siahaan", "phoneNumber" => "81237485099", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "99", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Jl. GHM Siahaan", 'pemungut_id' => 1),
            array("id" => "100", "name" => "HKBP Distrik", "email" => "", "username" => "hkbp_distrik", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Paindoan", "phoneNumber" => "81237485100", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "100", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Jl. Paindoan", 'pemungut_id' => 1),
            array("id" => "101", "name" => "Hana Jaya", "email" => "", "username" => "hana_jaya", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Paindoan", "phoneNumber" => "81237485101", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "101", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Jl. Paindoan", 'pemungut_id' => 1),
            array("id" => "102", "name" => "Warung Nova", "email" => "", "username" => "warung_nova", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Paindoan", "phoneNumber" => "81237485102", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "102", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Jl. Paindoan", 'pemungut_id' => 1),
            array("id" => "103", "name" => "K. Tampubolon", "email" => "", "username" => "k_tampubolon", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Paindoan", "phoneNumber" => "81237485103", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "103", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Jl. Paindoan", 'pemungut_id' => 1),
            array("id" => "104", "name" => "Ondi Tambunan", "email" => "", "username" => "ondi_tambunan", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Paindoan", "phoneNumber" => "81237485104", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "104", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Jl. Paindoan", 'pemungut_id' => 1),
            array("id" => "105", "name" => "A. Pasaribu", "email" => "", "username" => "a_pasaribu", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Cornel S", "phoneNumber" => "81237485105", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "105", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Jl. Cornel S", 'pemungut_id' => 1),
            array("id" => "106", "name" => "Ma Bastian", "email" => "", "username" => "ma_bastian", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Cornel S", "phoneNumber" => "81237485106", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "106", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Jl. Cornel S", 'pemungut_id' => 1),
            array("id" => "107", "name" => "Pak Ando", "email" => "", "username" => "pak_ando", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Cornel S", "phoneNumber" => "81237485107", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "107", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Jl. Cornel S", 'pemungut_id' => 1),
            array("id" => "108", "name" => "Op. Maranata", "email" => "", "username" => "op_maranata", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Cornel S", "phoneNumber" => "81237485108", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "108", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Jl. Cornel S", 'pemungut_id' => 1),
            array("id" => "109", "name" => "R. Silitonga", "email" => "", "username" => "r_silitonga", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Gang dame", "phoneNumber" => "81237485109", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "109", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Jl. Gang dame", 'pemungut_id' => 1),
            array("id" => "110", "name" => "P Pangaribuan", "email" => "", "username" => "p_pangaribuan", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Gang dame", "phoneNumber" => "81237485110", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "110", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Jl. Gang dame", 'pemungut_id' => 1),
            array("id" => "111", "name" => "P. Panjaitan", "email" => "", "username" => "p_panjaitan", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Gang dame", "phoneNumber" => "81237485111", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "111", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Jl. Gang dame", 'pemungut_id' => 1),
            array("id" => "112", "name" => "C, Sirait", "email" => "", "username" => "p_sirait", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Gang dame", "phoneNumber" => "81237485112", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "112", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Jl. Gang dame", 'pemungut_id' => 1),
            array("id" => "113", "name" => "L. Nababan", "email" => "", "username" => "l_nababan", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Gang dame", "phoneNumber" => "81237485113", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "113", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Jl. Gang dame", 'pemungut_id' => 1),
            array("id" => "114", "name" => "Ma Muel", "email" => "", "username" => "ma_muel", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Gang dame", "phoneNumber" => "81237485114", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "114", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Jl. Gang dame", 'pemungut_id' => 1),
            array("id" => "115", "name" => "D Simbolon", "email" => "", "username" => "d_simbolon", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Gang dame", "phoneNumber" => "81237485115", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "115", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Jl. Gang dame", 'pemungut_id' => 1),
            array("id" => "116", "name" => "M. Situmorang", "email" => "", "username" => "m_situmorang", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Gang dame", "phoneNumber" => "81237485116", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "116", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Jl. Gang dame", 'pemungut_id' => 1),
            array("id" => "117", "name" => "Op. Lisbet M", "email" => "", "username" => "op_lisbet_m", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Gang dame", "phoneNumber" => "81237485117", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "117", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Jl. Gang dame", 'pemungut_id' => 1),
            array("id" => "118", "name" => "Mega Siahaan", "email" => "", "username" => "mega_siahaan", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Perum tani jaya", "phoneNumber" => "81237485118", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "118", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Perum tani jaya", 'pemungut_id' => 1),
            array("id" => "119", "name" => "S. Sihotang", "email" => "", "username" => "s_sihotang", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Perum tani jaya", "phoneNumber" => "81237485119", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "119", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Perum tani jaya", 'pemungut_id' => 1),
            array("id" => "120", "name" => "M. Sinurat", "email" => "", "username" => "m_sinurat", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Perum tani jaya", "phoneNumber" => "81237485120", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "120", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Perum tani jaya", 'pemungut_id' => 1),
            array("id" => "121", "name" => "C. Tambunan", "email" => "", "username" => "c_tambunan", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Perum tani jaya", "phoneNumber" => "81237485121", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "121", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Perum tani jaya", 'pemungut_id' => 1),
            array("id" => "122", "name" => "M. Situmeang", "email" => "", "username" => "m_situmeang", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Perum tani jaya", "phoneNumber" => "81237485122", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "122", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Perum tani jaya", 'pemungut_id' => 1),
            array("id" => "123", "name" => "M. Panjaitan", "email" => "", "username" => "m_panjaitan", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Perum tani jaya", "phoneNumber" => "81237485123", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "123", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Perum tani jaya", 'pemungut_id' => 1),
            array("id" => "124", "name" => "P. Hutabarat", "email" => "", "username" => "p_hutabarat", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Perum tani jaya", "phoneNumber" => "81237485124", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "124", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Perum tani jaya", 'pemungut_id' => 1),
            array("id" => "125", "name" => "Saragi", "email" => "", "username" => "saragi", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Perum tani jaya", "phoneNumber" => "81237485125", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "125", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Perum tani jaya", 'pemungut_id' => 1),
            array("id" => "126", "name" => "Jai Ginting", "email" => "", "username" => "jai_ginting", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Perum tani jaya", "phoneNumber" => "81237485126", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "126", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Perum tani jaya", 'pemungut_id' => 1),
            array("id" => "127", "name" => "Ma Jery", "email" => "", "username" => "ma_jery", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Sibagotnipohan", "phoneNumber" => "81237485127", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "127", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Jl. Sibagotnipohan", 'pemungut_id' => 1),
            array("id" => "128", "name" => "Op. Marihot", "email" => "", "username" => "op_marihot", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Sibagotnipohan", "phoneNumber" => "81237485128", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "128", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Jl. Sibagotnipohan", 'pemungut_id' => 1),
            array("id" => "129", "name" => "Rizky", "email" => "", "username" => "rizky", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Sibagotnipohan", "phoneNumber" => "81237485129", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "129", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Jl. Sibagotnipohan", 'pemungut_id' => 1),
            array("id" => "130", "name" => "R.s Simangunsong", "email" => "", "username" => "r_s_simangunsong", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Sibagotnipohan", "phoneNumber" => "81237485130", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "130", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Jl. Sibagotnipohan", 'pemungut_id' => 1),
            array("id" => "131", "name" => "Vespa Panjaitan", "email" => "", "username" => "vespa_panjaitan", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Sibagotnipohan", "phoneNumber" => "81237485131", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "131", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Jl. Sibagotnipohan", 'pemungut_id' => 1),
            array("id" => "132", "name" => "Daniel Siahaan", "email" => "", "username" => "daniel_siahaan", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Sibagotnipohan", "phoneNumber" => "81237485132", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "132", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Jl. Sibagotnipohan", 'pemungut_id' => 1),
            array("id" => "133", "name" => "C. Panjaitan", "email" => "", "username" => "c_panjaitan", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Sibagotnipohan", "phoneNumber" => "81237485133", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "133", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Jl. Sibagotnipohan", 'pemungut_id' => 1),
            array("id" => "134", "name" => "Ratna", "email" => "", "username" => "ratna", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Sibagotnipohan", "phoneNumber" => "81237485134", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "134", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Jl. Sibagotnipohan", 'pemungut_id' => 1),
            array("id" => "135", "name" => "P. Pebriani", "email" => "", "username" => "p_pebriani", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Sibagotnipohan", "phoneNumber" => "81237485135", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "135", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Jl. Sibagotnipohan", 'pemungut_id' => 1),
            array("id" => "136", "name" => "A. Flora", "email" => "", "username" => "a_flora", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Sibagotnipohan", "phoneNumber" => "81237485136", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "136", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Jl. Sibagotnipohan", 'pemungut_id' => 1),
            array("id" => "137", "name" => "R. Naibaho", "email" => "", "username" => "r_naibaho", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Sibagotnipohan", "phoneNumber" => "81237485137", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "137", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Jl. Sibagotnipohan", 'pemungut_id' => 1),
            array("id" => "138", "name" => "Pak Gress", "email" => "", "username" => "pak_gress", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Sibagotnipohan", "phoneNumber" => "81237485138", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "138", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Jl. Sibagotnipohan", 'pemungut_id' => 1),
            array("id" => "139", "name" => "S. Sianipar", "email" => "", "username" => "s_sianipar", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Sibagotnipohan", "phoneNumber" => "81237485139", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "139", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Jl. Sibagotnipohan", 'pemungut_id' => 1),
            array("id" => "140", "name" => "S.B. Napitupulu", "email" => "", "username" => "s_b_napitupulu", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Sibagotnipohan", "phoneNumber" => "81237485140", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "140", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Jl. Sibagotnipohan", 'pemungut_id' => 1),
            array("id" => "141", "name" => "Warung Ma Nanta", "email" => "", "username" => "warung_ma_nanta", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Sibagotnipohan", "phoneNumber" => "81237485141", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "141", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Jl. Sibagotnipohan", 'pemungut_id' => 1),
            array("id" => "142", "name" => "Nuri. S", "email" => "", "username" => "nuri_s", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Sibagotnipohan", "phoneNumber" => "81237485142", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "142", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Jl. Sibagotnipohan", 'pemungut_id' => 1),
            array("id" => "143", "name" => "Carli Siahaan", "email" => "", "username" => "carli_siahaan", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Sibagotnipohan", "phoneNumber" => "81237485143", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "143", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Jl. Sibagotnipohan", 'pemungut_id' => 1),
            array("id" => "144", "name" => "Robet Siahaan", "email" => "", "username" => "robert_siahaan", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Sibagotnipohan", "phoneNumber" => "81237485144", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "144", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Jl. Sibagotnipohan", 'pemungut_id' => 1),
            array("id" => "145", "name" => "J. Sitorus", "email" => "", "username" => "j_sitorus", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Adyaksa", "phoneNumber" => "81237485145", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "145", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Jl. Adyaksa", 'pemungut_id' => 1),
            array("id" => "146", "name" => "Ma Anwar", "email" => "", "username" => "ma_anwar", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Adyaksa", "phoneNumber" => "81237485146", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "146", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Jl. Adyaksa", 'pemungut_id' => 1),
            array("id" => "147", "name" => "M. Hutajulu", "email" => "", "username" => "m_hutajulu", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Adyaksa", "phoneNumber" => "81237485147", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "147", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Jl. Adyaksa", 'pemungut_id' => 1),
            array("id" => "148", "name" => "B. Hutapea", "email" => "", "username" => "b_hutapea", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Adyaksa", "phoneNumber" => "81237485148", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "148", "category_id" => "1", "sub_district_id" => "1", "address_uc" => "Jl. Adyaksa", 'pemungut_id' => 1),
            array("id" => "149", "name" => "R.M. Sopoyono", "email" => "", "username" => "r_m_sopoyono", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. SM Raja", "phoneNumber" => "81237485149", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "149", "category_id" => "3", "sub_district_id" => "1", "address_uc" => "Jl. SM Raja", 'pemungut_id' => 1),
            array("id" => "150", "name" => "Toko Ma Kembar", "email" => "", "username" => "toko_ma_kembar", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Patuan Anggi", "phoneNumber" => "81237485150", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "150", "category_id" => "3", "sub_district_id" => "1", "address_uc" => "Jl. Patuan Anggi", 'pemungut_id' => 1),
            array("id" => "151", "name" => "Warung bakso Saripa", "email" => "", "username" => "warung_bakso_saripa", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Patuan Anggi", "phoneNumber" => "81237485151", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "151", "category_id" => "3", "sub_district_id" => "1", "address_uc" => "Jl. Patuan Anggi", 'pemungut_id' => 1),
            array("id" => "152", "name" => "Kedai Mi Lily", "email" => "", "username" => "kedai_mi_lily", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Gereja", "phoneNumber" => "81237485152", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "152", "category_id" => "3", "sub_district_id" => "1", "address_uc" => "Jl. Gereja", 'pemungut_id' => 1),
            array("id" => "153", "name" => "Dapot baby Shop", "email" => "", "username" => "dapot_baby_shop", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Gereja", "phoneNumber" => "81237485153", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "153", "category_id" => "3", "sub_district_id" => "1", "address_uc" => "Jl. Gereja", 'pemungut_id' => 1),
            array("id" => "154", "name" => "Rumah makan Panca", "email" => "", "username" => "rumah_makan_panca", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Paindoan", "phoneNumber" => "81237485154", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "154", "category_id" => "3", "sub_district_id" => "1", "address_uc" => "Jl. Paindoan", 'pemungut_id' => 1),
            array("id" => "155", "name" => "Rume.comah makan Nasional", "email" => "", "username" => "rumah_makan_nasional", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Gereja", "phoneNumber" => "81237485155", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "155", "category_id" => "3", "sub_district_id" => "1", "address_uc" => "Jl. Gereja", 'pemungut_id' => 1),
            array("id" => "156", "name" => "Rumah makan Masyono", "email" => "", "username" => "rumah_makan_masyono", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Gereja", "phoneNumber" => "81237485156", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "156", "category_id" => "3", "sub_district_id" => "1", "address_uc" => "Jl. Gereja", 'pemungut_id' => 1),
            array("id" => "157", "name" => "Rumah makan P. Pasaribu", "email" => "", "username" => "rumah_makan_p_pasaribu", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Gereja", "phoneNumber" => "81237485157", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "157", "category_id" => "3", "sub_district_id" => "1", "address_uc" => "Jl. Gereja", 'pemungut_id' => 1),
            array("id" => "158", "name" => "Rumah makan Ayam kejar", "email" => "", "username" => "rumah_makan_ayam_kejar", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Gereja", "phoneNumber" => "81237485158", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "158", "category_id" => "3", "sub_district_id" => "1", "address_uc" => "Jl. Gereja", 'pemungut_id' => 1),
            array("id" => "159", "name" => "Warnet", "email" => "", "username" => "warnet", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Gereja", "phoneNumber" => "81237485159", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "159", "category_id" => "3", "sub_district_id" => "1", "address_uc" => "Jl. Gereja", 'pemungut_id' => 1),
            array("id" => "160", "name" => "D'baran Cafe", "email" => "", "username" => "dbaran_cafe", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Gereja", "phoneNumber" => "81237485160", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "160", "category_id" => "3", "sub_district_id" => "1", "address_uc" => "Jl. Gereja", 'pemungut_id' => 1),
            array("id" => "161", "name" => "BRI Unit", "email" => "", "username" => "bri_unit", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Patuan Anggi", "phoneNumber" => "81237485161", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "161", "category_id" => "6", "sub_district_id" => "1", "address_uc" => "Jl. Patuan Anggi", 'pemungut_id' => 1),
            array("id" => "162", "name" => "Bank SUMUT", "email" => "", "username" => "bank_sumut", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. SM Raja", "phoneNumber" => "81237485162", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "162", "category_id" => "6", "sub_district_id" => "1", "address_uc" => "Jl. SM Raja", 'pemungut_id' => 1),
            array("id" => "163", "name" => "Hotel Marsaringar", "email" => "", "username" => "hotel_marsaringar", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Gereja", "phoneNumber" => "81237485163", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "163", "category_id" => "4", "sub_district_id" => "1", "address_uc" => "Jl. Gereja", 'pemungut_id' => 1),
            array("id" => "164", "name" => "Losmen Generasi", "email" => "", "username" => "losmen_generasi", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Sibagotnipohan", "phoneNumber" => "81237485164", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "164", "category_id" => "4", "sub_district_id" => "1", "address_uc" => "Jl. Sibagotnipohan", 'pemungut_id' => 1),
            array("id" => "165", "name" => "Dinas Kesehatan", "email" => "", "username" => "dinas_kesehatan", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Somba Debata", "phoneNumber" => "81237485165", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "165", "category_id" => "5", "sub_district_id" => "1", "address_uc" => "Jl. Somba Debata", 'pemungut_id' => 1),
            array("id" => "166", "name" => "Diakones", "email" => "", "username" => "diakones", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Gereja", "phoneNumber" => "81237485166", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "166", "category_id" => "19", "sub_district_id" => "1", "address_uc" => "Jl. Gereja", 'pemungut_id' => 1),
            array("id" => "167", "name" => "Asrama RS. HKBP", "email" => "", "username" => "asrama_rs_hkbp", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Gereja", "phoneNumber" => "81237485167", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "167", "category_id" => "19", "sub_district_id" => "1", "address_uc" => "Jl. Gereja", 'pemungut_id' => 1),
            array("id" => "168", "name" => "Alfamidi", "email" => "", "username" => "alfamidi", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Gereja", "phoneNumber" => "81237485168", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "168", "category_id" => "15", "sub_district_id" => "1", "address_uc" => "Jl. Gereja", 'pemungut_id' => 1),
            array("id" => "169", "name" => "RS HKBP", "email" => "", "username" => "rs_hkbp", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. Gereja", "phoneNumber" => "81237485169", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "169", "category_id" => "8", "sub_district_id" => "1", "address_uc" => "Jl. Gereja", 'pemungut_id' => 1),
            array("id" => "170", "name" => "SD HKBD", "email" => "", "username" => "sd_hkbd", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. DS. GHM Siahaan", "phoneNumber" => "81237485170", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "170", "category_id" => "7", "sub_district_id" => "1", "address_uc" => "Jl. DS. GHM Siahaan", 'pemungut_id' => 1),
            array("id" => "171", "name" => "SD 173522", "email" => "", "username" => "sd_173522", "password" => "", "nik" => "", "gender" => "Laki-Laki", "address" => "Jl. DS. GHM Siahaan", "phoneNumber" => "81237485171", "sub_district_id" => "1", "district_id" => "1", "status" => "1", "user_id" => "171", "category_id" => "7", "sub_district_id" => "1", "address_uc" => "Jl. DS. GHM Siahaan", 'pemungut_id' => 1),
            [
                "id" => "172",
                "name" => "B. Simajuntak",
                "email" => "",
                "password" => "",
                "nik" => "",
                "gender" => "Laki-Laki",
                "address" => "Parsuratan",
                "phoneNumber" => "81237485172",
                "sub_district_id" => "2",
                "district_id" => "1",
                "status" => "1",
                "user_id" => "172",
                "category_id" => "1",
                "pemungut_id" => "7",
            ],
            [
                "id" => "173",
                "name" => "H. Simajuntak",
                "email" => "",
                "password" => "",
                "nik" => "",
                "gender" => "Laki-Laki",
                "address" => "Parsuratan",
                "phoneNumber" => "81237485173",
                "sub_district_id" => "2",
                "district_id" => "1",
                "status" => "1",
                "user_id" => "173",
                "category_id" => "1",
                "pemungut_id" => "7",
            ],
            [
                "id" => "174",
                "name" => "G.M Siahaan",
                "email" => "",
                "password" => "",
                "nik" => "",
                "gender" => "Laki-Laki",
                "address" => "Paindoan",
                "phoneNumber" => "81237485174",
                "sub_district_id" => "2",
                "district_id" => "1",
                "status" => "1",
                "user_id" => "174",
                "category_id" => "1",
                "pemungut_id" => "7",
            ],
            [
                "id" => "175",
                "name" => "Binsar M",
                "email" => "",
                "password" => "",
                "nik" => "",
                "gender" => "Laki-Laki",
                "address" => "Paindoan",
                "phoneNumber" => "81237485175",
                "sub_district_id" => "2",
                "district_id" => "1",
                "status" => "1",
                "user_id" => "175",
                "category_id" => "1",
                "pemungut_id" => "7",
            ],
            [
                "id" => "176",
                "name" => "P. Hutagaol",
                "email" => "",
                "password" => "",
                "nik" => "",
                "gender" => "Laki-Laki",
                "address" => "Paindoan",
                "phoneNumber" => "81237485176",
                "sub_district_id" => "2",
                "district_id" => "1",
                "status" => "1",
                "user_id" => "176",
                "category_id" => "1",
                "pemungut_id" => "7",
            ],
            [
                "id" => "177",
                "name" => "Scorpio",
                "email" => "",
                "password" => "",
                "nik" => "",
                "gender" => "Laki-Laki",
                "address" => "Onan Sampang",
                "phoneNumber" => "81237485177",
                "sub_district_id" => "2",
                "district_id" => "1",
                "status" => "1",
                "user_id" => "177",
                "category_id" => "1",
                "pemungut_id" => "7",
            ],
            [
                "id" => "178",
                "name" => "Nira S",
                "email" => "",
                "password" => "",
                "nik" => "",
                "gender" => "Laki-Laki",
                "address" => "Onan Sampang",
                "phoneNumber" => "81237485178",
                "sub_district_id" => "2",
                "district_id" => "1",
                "status" => "1",
                "user_id" => "178",
                "category_id" => "1",
                "pemungut_id" => "7",
            ],
            [
                "id" => "179",
                "name" => "R. Siahaan",
                "email" => "",
                "password" => "",
                "nik" => "",
                "gender" => "Laki-Laki",
                "address" => "Onan Sampang",
                "phoneNumber" => "81237485179",
                "sub_district_id" => "2",
                "district_id" => "1",
                "status" => "1",
                "user_id" => "179",
                "category_id" => "1",
                "pemungut_id" => "7",
            ],
            [
                "id" => "180",
                "name" => "J. Simanjuntak",
                "email" => "",
                "password" => "",
                "nik" => "",
                "gender" => "Laki-Laki",
                "address" => "Parsuratan",
                "phoneNumber" => "81237485180",
                "sub_district_id" => "2",
                "district_id" => "1",
                "status" => "1",
                "user_id" => "180",
                "category_id" => "1",
                "pemungut_id" => "7",
            ],
            [
                "id" => "181",
                "name" => "Nanda Ulos",
                "email" => "",
                "password" => "",
                "nik" => "",
                "gender" => "Laki-Laki",
                "address" => "Sibulele",
                "phoneNumber" => "81237485181",
                "sub_district_id" => "2",
                "district_id" => "1",
                "status" => "1",
                "user_id" => "181",
                "category_id" => "1",
                "pemungut_id" => "7",
            ],
            [
                "id" => "182",
                "name" => "Stars",
                "email" => "",
                "password" => "",
                "nik" => "",
                "gender" => "Laki-Laki",
                "address" => "Jl. Sisingamangaraja",
                "phoneNumber" => "81237485182",
                "sub_district_id" => "2",
                "district_id" => "1",
                "status" => "1",
                "user_id" => "182",
                "category_id" => "3",
                "pemungut_id" => "2",
            ],
            [
                "id" => "183",
                "name" => "Sejahtera",
                "email" => "",
                "password" => "",
                "nik" => "",
                "gender" => "Laki-Laki",
                "address" => "Jl. Sisingamangaraja",
                "phoneNumber" => "81237485183",
                "sub_district_id" => "2",
                "district_id" => "1",
                "status" => "1",
                "user_id" => "183",
                "category_id" => "3",
                "pemungut_id" => "2",
            ],
            [
                "id" => "184",
                "name" => "Generasi",
                "email" => "",
                "password" => "",
                "nik" => "",
                "gender" => "Laki-Laki",
                "address" => "Jl. Sisingamangaraja",
                "phoneNumber" => "81237485184",
                "sub_district_id" => "2",
                "district_id" => "1",
                "status" => "1",
                "user_id" => "184",
                "category_id" => "3",
                "pemungut_id" => "2",
            ],
            [
                "id" => "185",
                "name" => "Ramli Siregar",
                "email" => "",
                "password" => "",
                "nik" => "",
                "gender" => "Laki-Laki",
                "address" => "Jl. Sisingamangaraja",
                "phoneNumber" => "81237485185",
                "sub_district_id" => "2",
                "district_id" => "1",
                "status" => "1",
                "user_id" => "185",
                "category_id" => "3",
                "pemungut_id" => "2",
            ],
            [
                "id" => "186",
                "name" => "Fhakira",
                "email" => "",
                "password" => "",
                "nik" => "",
                "gender" => "Laki-Laki",
                "address" => "Jl. Sisingamangaraja",
                "phoneNumber" => "81237485186",
                "sub_district_id" => "2",
                "district_id" => "1",
                "status" => "1",
                "user_id" => "186",
                "category_id" => "3",
                "pemungut_id" => "2",
            ],
            [
                "id" => "187",
                "name" => "Chandra",
                "email" => "",
                "password" => "",
                "nik" => "",
                "gender" => "Laki-Laki",
                "address" => "Jl. Sisingamangaraja",
                "phoneNumber" => "81237485187",
                "sub_district_id" => "2",
                "district_id" => "1",
                "status" => "1",
                "user_id" => "187",
                "category_id" => "3",
                "pemungut_id" => "2",
            ],
            [
                "id" => "188",
                "name" => "Duma",
                "email" => "",
                "password" => "",
                "nik" => "",
                "gender" => "Laki-Laki",
                "address" => "Jl. Sisingamangaraja",
                "phoneNumber" => "81237485188",
                "sub_district_id" => "2",
                "district_id" => "1",
                "status" => "1",
                "user_id" => "188",
                "category_id" => "3",
                "pemungut_id" => "2",
            ],
            [
                "id" => "189",
                "name" => "Ratna",
                "email" => "",
                "password" => "",
                "nik" => "",
                "gender" => "Laki-Laki",
                "address" => "Jl. Sisingamangaraja",
                "phoneNumber" => "81237485189",
                "sub_district_id" => "2",
                "district_id" => "1",
                "status" => "1",
                "user_id" => "189",
                "category_id" => "3",
                "pemungut_id" => "2",
            ],
            [
                "id" => "190",
                "name" => "Mulia Jaya",
                "email" => "",
                "password" => "",
                "nik" => "",
                "gender" => "Laki-Laki",
                "address" => "Jl. Sisingamangaraja",
                "phoneNumber" => "81237485190",
                "sub_district_id" => "2",
                "district_id" => "1",
                "status" => "1",
                "user_id" => "190",
                "category_id" => "3",
                "pemungut_id" => "2",
            ],
            [
                "id" => "191",
                "name" => "Amory",
                "email" => "",
                "password" => "",
                "nik" => "",
                "gender" => "Laki-Laki",
                "address" => "Jl. Sisingamangaraja",
                "phoneNumber" => "81237485191",
                "sub_district_id" => "2",
                "district_id" => "1",
                "status" => "1",
                "user_id" => "191",
                "category_id" => "3",
                "pemungut_id" => "2"
            ]
        ),
    ],
];
